---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
  - name: Update S3 code bucket
    command: aws s# sync /var/www/html s3://{{ s3code }}/ --delete
  - shell: echo "define('WP_SITEURL', 'http:/dev.'"{{ domain }}".com;" >> wp-config.php
    args: 
      chdir: /var/www/html
  - shell:
    args:
      chdir: /var/www/html